twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/custom_types/tinymce.html.twig'
        - 'form/custom_types/checkbox.html.twig'

when@test:
    twig:
        strict_variables: true
